name: Efccreative
favicon: null
layout_spectrum: 0.457385737914592
typography_spectrum: 0.6702421922236681
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5385a'
    - '#0fc76d'
    - '#2436c6'
    - '#440852'
    - '#d2a22b'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.738275591051206
purpose: []
